name: tagged release

on:
  push:
    tags:
      - "v*.*.*"

env:
  IMAGE_NAME_TF: "koi-core-tf"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout code"
        uses: actions/checkout@v3
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: "install dependencies"
        run: pip install build
      
      - name: "build wheel and source distribution"
        run: python -m build
      
      - name: "build docker image"
        run: docker build . --file cpu-tf.Dockerfile --tag $IMAGE_NAME_TF --label "runnumber=${GITHUB_RUN_ID}"

      - name: publish the package as Release v*.*.*
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Release ${{ github.ref_name }}"
          files: |
            dist/koi_core-*.whl
            dist/koi-core-*.tar.gz
      
      - name: "publish docker image"
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME_TF

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME_TF $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION