name: tagged release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout code"
        uses: actions/checkout@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: "install dependencies"
        run: pip install build
      
      - name: "build wheel and source distribution"
        run: python -m build

      - name: publish the package
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release ${{ env.GITHUB_REF_NAME }}"
          files: |
            dist/koi_core-*.whl
            dist/koi-core-*.tar.gz